name: Runs the project tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Oracle JDK 21'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: 'Grant Permission for Gradle'
        run: chmod +x gradlew
      - name: 'Build with Gradle'
        run: ./gradlew build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Oracle JDK 21'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: 'Grant Permission for Gradle'
        run: chmod +x gradlew
      - name: 'Test with Gradle'
        run: ./gradlew test