name: Publish to maven on merged pull request

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Oracle JDK 21'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: 'Grant Permission for Gradle'
        run: chmod +x gradlew
      - name: 'Build with Gradle'
        run: ./gradlew build
  test:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Oracle JDK 21'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: 'Grant Permission for Gradle'
        run: chmod +x gradlew
      - name: 'Test with Gradle'
        run: ./gradlew test
  publish:
    if: github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Oracle JDK 21'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: 'Grant Permission for Gradle'
        run: chmod +x gradlew
      - name: 'Publish with Gradle'
        run: ./gradlew publish